"""Reference solutions for the statistics problem set."""

from __future__ import annotations

from collections import Counter
from math import comb
from typing import Any


def binomial_exact_test(
    n_samples: int,
    n_positive_samples: int,
    proposed_value: float,
) -> float:
    """Compute a one-tailed exact binomial test p-value.

    Test:

        H_0: p = proposed_value
        H_a: p > proposed_value

    The returned p-value is P(X >= n_positive_samples) for

        X ~ Binomial(n_samples, proposed_value)
    """
    if n_samples < 1:
        raise ValueError("n_samples must be positive.")

    if not 0 <= n_positive_samples <= n_samples:
        raise ValueError("n_positive_samples must be between 0 and n_samples.")

    if not 0 <= proposed_value <= 1:
        raise ValueError("proposed_value must be between 0 and 1.")

    return sum(
        comb(n_samples, successes)
        * proposed_value**successes
        * (1 - proposed_value) ** (n_samples - successes)
        for successes in range(n_positive_samples, n_samples + 1)
    )


def _dice_sum_counts(n_dice: int, sides: int = 6) -> Counter[int]:
    """Count ways to produce each total when rolling n_dice fair dice."""
    if n_dice < 1:
        raise ValueError("n_dice must be positive.")

    if sides < 2:
        raise ValueError("sides must be at least 2.")

    counts = Counter({0: 1})

    for _ in range(n_dice):
        next_counts: Counter[int] = Counter()

        for current_total, count in counts.items():
            for face in range(1, sides + 1):
                next_counts[current_total + face] += count

        counts = next_counts

    return counts


def _upper_tail_probability_for_18d6(total_score: int) -> float:
    """Return P(sum of 18 fair six-sided dice >= total_score)."""
    counts = _dice_sum_counts(n_dice=18, sides=6)
    total_outcomes = 6**18

    favorable_outcomes = sum(
        count for score, count in counts.items() if score >= total_score
    )

    return favorable_outcomes / total_outcomes


def _parse_attribute_scores(attribute_stats: dict[str, Any]) -> dict[str, int]:
    """Validate and parse six D&D-style ability scores."""
    if len(attribute_stats) != 6:
        raise ValueError("attribute_stats must contain exactly six attributes.")

    parsed_scores = {}

    for attribute, raw_score in attribute_stats.items():
        try:
            score = int(raw_score)
        except (TypeError, ValueError) as error:
            raise ValueError(f"{attribute} must be an integer-like value.") from error

        if not 3 <= score <= 18:
            raise ValueError(f"{attribute} must be between 3 and 18.")

        parsed_scores[attribute] = score

    return parsed_scores


def test_for_cheating(
    attribute_stats: dict[str, Any],
    alpha: float = 0.05,
) -> dict[str, Any]:
    """Test whether D&D-style ability scores are unusually high.

    Assumption:

    - Each of six attributes is generated by rolling 3d6.
    - Therefore, the total score is the sum of 18 fair six-sided dice.

    The test uses an upper-tail exact probability:

        P(total score from 18d6 >= observed total score)

    This is a heuristic screen, not proof of cheating.
    """
    if not 0 < alpha < 1:
        raise ValueError("alpha must be between 0 and 1.")

    parsed_scores = _parse_attribute_scores(attribute_stats)
    total_score = sum(parsed_scores.values())
    mean_score = total_score / len(parsed_scores)
    p_value = _upper_tail_probability_for_18d6(total_score)
    suspicious = p_value < alpha

    if suspicious:
        reason = "The total score is unusually high under a 3d6-per-attribute model."
    else:
        reason = (
            "No strong evidence that the total score is unusually high under "
            "a 3d6-per-attribute model."
        )

    return {
        "scores": parsed_scores,
        "total_score": total_score,
        "mean_score": mean_score,
        "p_value": p_value,
        "alpha": alpha,
        "suspicious": suspicious,
        "reason": reason,
    }


test_for_cheating.__test__ = False
